### READ MASTER EMPLOYEES
GET http://localhost:1250/employees
Content-Type: application/json
Accept: application/json

### CREATE MASTER EMPLOYEE
POST http://localhost:1250/employee
Content-Type: application/json
Accept: application/json

{
    "name": "tatang kolep",
    "dept_id": "55",
    "level": "5",
    "join_date": "2022-03-03",
    "address": "Bandung Coret",
    "email": "btidev01@protonmail.com",
    "phone": "0818020241572",
    "dob": "1980-12-12",
    "pob": "Wamena"
}

### UPDATE MASTER EMPLOYEE
PUT http://localhost:1250/employee/20220303007
Content-Type: application/json
Accept: application/json

{
    "name": "udin beton 2",
    "dept_id": "55",
    "level": "5",
    "join_date": "2022-03-03",
    "address": "Bandung Coret",
    "email": "btidev01@protonmail.com",
    "phone": "0818020241572",
    "dob": "1980-12-12",
    "pob": "Wamena"
}

### ACTIVATE / INACTIVATE MASTER EMPLOYEE
PATCH http://localhost:1250/employee/activate/20220303004
Content-Type: application/json
Accept: application/json